name: Caddy Docker Image CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'caddy/*'
      - '.github/workflows/caddy.yml'
  pull_request:
    branches: [ master ]
    paths: 
      - 'caddy/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set version if empty
        id: set_version
        run: |
          if [ -n "${{ github.event.inputs.build_version }}" ]; then
            CADDY_VERSION=$(echo "${{ github.event.inputs.build_version }}" | sed 's/^v//')
          elif [ -n "${{ github.event.client_payload.latest_version }}" ]; then
            CADDY_VERSION=$(echo "${{ github.event.client_payload.latest_version }}" | sed 's/^v//')
          else
            CADDY_VERSION=$(cat version)
          fi
          echo "CADDY_VERSION=$CADDY_VERSION" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./caddy
          platforms: linux/amd64
          push: true
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-diy:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-diy:${{ env.CADDY_VERSION }}
